# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a670dfb6eefbdfb62de7d35ed5d520d3caf470b0c4e83c5fa3801ee3ba7d10843c90187f5993779b0dac60ad271b677ce89ca333561605763f5b8cc6c43899d

test:
  secret_key_base: 371acb5a87e69299518a755a03b3b2f84553b00cc09956d0255a421df54256e7511e227fcb9f2e82490733ed57df5384165599cbf078c8be8336263dd38203cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
